config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'visitors#index'

  resources :sales
  resources :customers
  resources :supliers
  resources :users
  resources :debit_notes
  

  post '/customer/report' => 'customers#customerReport', :as => :customer_report
  post '/allCustomers/report' => 'customers#allCustomersReport'

  post '/sale/:id/report' => 'reports#saleReport', :as => :sale_report
  post '/suplier_sale/:id/report' => 'reports#suplierSaleReport', :as => :suplier_sale_report
  post '/customer_sale/:id/report' => 'reports#customerSaleReport', :as => :customer_sale_report
  post '/allSales/report' => 'reports#allSalesReport'

  post '/suplier/:id/report' => 'supliers#suplierReport', :as => :suplier_report
  post '/allSupliers/report' => 'supliers#allSupliersReport'

  post '/user/create' => 'users#create', :as => :user_create

  get 'debit_note/update_sales' => 'debit_notes#update_sales', :as => :update_sales

end

app/models/debit_note.rb
class DebitNote < ActiveRecord::Base
  belongs_to :customer
  has_many :fixations    
  has_many :sales, :through => :fixations

  accepts_nested_attributes_for :fixations, :sales
  validates :customer_id, presence: true
end

app/controllers/debit_notes_controller.rb
class DebitNotesController < ApplicationController
  before_action :set_debit_note, only: [:show, :edit, :update, :destroy]

  # GET /debit_notes
  # GET /debit_notes.json
  def index
    @debit_notes = DebitNote.all
  end

  # GET /debit_notes/1
  # GET /debit_notes/1.json
  def show
  end

  # GET /debit_notes/new
  def new
    @debit_note = DebitNote.new
    @customers = Customer.all
    
    @sales_selected = Sale.select("sales.id, customer_contract").joins(:fixation).where("debit_note_id = 0")
    @sales_not_selected = Sale.joins(:fixation).where("customer_id = 0 and debit_note_id is null")

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render :json => @sales }
    end
    
  end

  # GET /debit_notes/1/edit
  def edit
    @customers = Customer.all
    #@sales_selected = Sale.select("sales.id, customer_contract").joins(:fixation).where("debit_note_id = ?", params[:id])
    #@sales_not_selected = Sale.joins(:fixation).where("customer_id = ? and debit_note_id is null", @debit_note.customer_id)
  end
  

  # POST /debit_notes
  # POST /debit_notes.json
  def create
    @debit_note = DebitNote.new(debit_note_params)
    @customers = Customer.all

    respond_to do |format|
      if @debit_note.save
        
        Fixation.joins(:sale).where("sale_id in (?)", params[:sales_selected]).update_all(debit_note_id: @debit_note.id)
        
        format.html { redirect_to @debit_note, notice: 'Debit note was successfully created.' }
        format.json { render :show, status: :created, location: @debit_note }
      else
        format.html { render :new }
        format.json { render json: @debit_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debit_notes/1
  # PATCH/PUT /debit_notes/1.json
  def update
    #raise params.inspect
    respond_to do |format|
      if @debit_note.update(debit_note_params)
        
        Fixation.where("debit_note_id = ?", params[:id]).update_all(debit_note_id: nil)
        Fixation.joins(:sale).where("sale_id in (?)", params[:debit_note][:id]).update_all(debit_note_id: params[:id])
        
        format.html { redirect_to @debit_note, notice: 'Debit note was successfully updated.' }
        format.json { render :show, status: :ok, location: @debit_note }
      else
        format.html { render :edit }
        format.json { render json: @debit_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debit_notes/1
  # DELETE /debit_notes/1.json
  def destroy
    
    Fixation.where("debit_note_id = ?", params[:id]).update_all(debit_note_id: nil)
    @debit_note.destroy
    
    respond_to do |format|
      format.html { redirect_to debit_notes_url, notice: 'Debit note was successfully destroyed.' }
      format.json { head :no_content }
    end
    
  end

  def update_sales

    @sales = Sale.joins(:fixation).where("debit_note_id IS NULL AND customer_id = ?", params[:customer_id])

    respond_to do |format|
      format.js
      #format.json { render json: @sales }
    end
  end


# ****************************************************************************************************************

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debit_note
      
      @debit_note = DebitNote.find(params[:id])
      @sales = Sale.joins(:fixation).where("debit_note_id = ?", params[:id])

      @sales_selected = Sale.select("sales.id, customer_contract").joins(:fixation).where("debit_note_id = ?", params[:id])
      @sales_not_selected = Sale.joins(:fixation).where("customer_id = ? and debit_note_id is null", @debit_note.customer_id)

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debit_note_params
      params.require(:debit_note).permit( :customer_id,
                                          :bank_info, 
                                          :total_ammount )
    end
end

app/helpers/debit_notes_helper.rb
module DebitNotesHelper
end

app/views/debit_notes/_form.html.erb
<%= form_for @debit_note, :html => { :class => "form-horizontal debit_note", :onsubmit => 'selectSales();' } do |f| %>

  <% if @debit_note.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@debit_note.errors.count, "error") %> prohibited this debit note from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @debit_note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :customer_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.collection_select(:customer_id, @customers, :id, :name, {:prompt=>'Selecione o Cliente'}, {:id=>'customers_select'}) %>
    </div>
    <%=f.error_span(:customer_id) %>
  </div>

  <div class="form-group">
    <%= f.label :bank_info, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_area :bank_info, :class => 'form-control' %>
    </div>
    <%=f.error_span(:bank_info) %>
  </div>
  <div class="form-group">
    <%= f.label :total_ammount, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :total_ammount, :class => 'form-control' %>
    </div>
    <%=f.error_span(:total_ammount) %>
  </div>

  <br>

  <div class="container" id="sales-form">

    <table>
      <tr valign="top">
        <td>
          <%= f.collection_select(:id, @sales_not_selected, :id, :customer_contract, {include_hidden: false}, {:multiple=>true, :id=>'s', :name=>'sales_not_selected', :style=>'width: 120px'}) %>
        </td>
        <td align="center" width="50px">
          <a href="#" onclick="listbox_moveacross('s', 'd')"><span class="glyphicon glyphicon-arrow-right"></span></a>
          <br/><br/>
          <a href="#" onclick="listbox_moveacross('d', 's')"><span class="glyphicon glyphicon-arrow-left"></span></a>
        </td>
        <td>
          <%= f.collection_select(:id, @sales_selected, :id, :customer_contract, {include_hidden: false}, {:multiple=>true, :id=>'d', :style=>'width: 120px'}) %>
        </td>
      </tr>
    </table>
  
  </div>

  <table>
    <tr align="left">
      <td width="100">&nbsp;</td>
      <td>
        <%=  image_submit_tag('confirm2.png', :border => 0, :alt => '', :title => t("helpers.links.save", :default => 'Save'), :width => 40, :height => 40) %>
      </td>
      <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td>
        <%= link_to image_tag('back.png', :border => 0, :alt => '', :title => t("helpers.links.cancel", :default => 'Cancel'), :width => 40, :height => 40),
                    debit_notes_path
        %>
      </td>
    </tr>
  </table>
<% end %>

<script type="text/javascript">

// ------------------------------------------------------------------------------------------------------------------
//
// DualListBox source: http://viralpatel.net/blogs/listbox-select-all-move-left-right-up-down-javascript/
//
// ------------------------------------------------------------------------------------------------------------------

  function listbox_moveacross(sourceID, destID) {
  	var src = document.getElementById(sourceID);
  	var dest = document.getElementById(destID);
  	for(var count=0; count < src.options.length; count++) {
  		if(src.options[count].selected == true) {
  				var option = src.options[count];
          var newOption = document.createElement("option"); 
          
          newOption.value = option.value; 
          newOption.text = option.text; 
          newOption.selected = true; 
          
          try { 
            dest.add(newOption, null); //Standard 
            src.remove(count, null); 
            
          }
          
          catch(error) { 
            dest.add(newOption); // IE only 
            src.remove(count);
          } count--; 
  		  
  		} 
  	}
  }

  function selectSales() {
      var multi = document.getElementById('d');
      for (var i = 0; i < multi.options.length; i++) {
          multi.options[i].selected = true;
      }
  }

// -------------------------------------------------------------------------------------------

</script>

app/views/debit_notes/edit.html.erb
<%- model_class = DebitNote -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/debit_notes/index.html.erb
<%- model_class = DebitNote -%>

<style>
#corpo {
    background-color:white;
    color:black;
}
</style>

<div id="corpo">
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%= model_class.human_attribute_name(:total_ammount) %></th>
        <th>Cliente</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @debit_notes.each do |dn| %>
        <tr>
          <td><%= link_to dn.id, debit_note_path(dn) %></td>
          <td><%= dn.created_at %></td>
          <td><%= dn.total_ammount %></td>
          <td><%= dn.customer.name %></td>
          <td>
            <%= link_to image_tag('edit.png', :border => 0, :alt => '', :title => t("views.debit_note.edit", :default => 'Edit Debit Note'), :width => 20, :height => 20),
                        edit_debit_note_path(dn)
            %>
          </td>
          <td>
            <%= link_to image_tag('delete.png', :border => 0, :alt => '', :title => t("views.debit_note.destroy", :default => 'Delete Debit Note'), :width => 20, :height => 20),
                        debit_note_path(dn),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure ?')) }
            %>
          
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table>
    <tr align="left">
      <td>
          <%= link_to image_tag('new.png', :border => 0, :alt => '', :title => t("views.debit_note.new", :default => 'New Debit Note'), :width => 40, :height => 40),
                      new_debit_note_path
          %>
      </td>
      <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <!--
      <td>
          <'%= link_to image_tag('printer.png', :border => 0, :alt => '', :title => t("views.customer.allReport", :default => 'Clients Report'), :width => 40, :height => 40),
                                allCustomers_report_path,
                                method: :post
          %>
      </td>
      -->
    </tr>
  </table>
</div>

app/views/debit_notes/new.html.erb
<%- model_class = DebitNote -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/debit_notes/show.html.erb
<%- model_class = DebitNote -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:bank_info) %>:</strong></dt>
  <dd><%= @debit_note.bank_info %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_ammount) %>:</strong></dt>
  <dd><%= @debit_note.total_ammount %></dd>
  <dt><strong>Nome de Cliente:</strong></dt>
  <dd><%= @debit_note.customer.name %></dd>
</dl>

<table>
<tr align="left">
  <td width="100">&nbsp;</td>
  <td>
    <%= link_to image_tag('back.png', :border => 0, :alt => '', :title => t("helpers.links.back", :default => 'Back'), :width => 40, :height => 40),
                debit_notes_path
    %>
  </td>
  <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
  <td>
      <%= link_to image_tag('edit.png', :border => 0, :alt => '', :title => t("views.sale.edit", :default => 'Edit Sale'), :width => 40, :height => 40),
                  edit_debit_note_path(@debit_note)
      %>
  </td>
  <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
  <td>
      <%= link_to image_tag('delete.png', :border => 0, :alt => '', :title => t("views.sale.destroy", :default => 'Delete Sale'), :width => 40, :height => 40),
                  debit_notes_path(@debit_note),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure ?')) }
      %>
  </td>
</tr>
</table>