config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'visitors#index'

  resources :sales
  resources :customers
  resources :supliers
  resources :users
  resources :debit_notes
  

  post '/customer/report' => 'customers#customerReport', :as => :customer_report
  post '/allCustomers/report' => 'customers#allCustomersReport'

  post '/sale/:id/report' => 'reports#saleReport', :as => :sale_report
  post '/suplier_sale/:id/report' => 'reports#suplierSaleReport', :as => :suplier_sale_report
  post '/customer_sale/:id/report' => 'reports#customerSaleReport', :as => :customer_sale_report
  post '/allSales/report' => 'reports#allSalesReport'

  post '/suplier/:id/report' => 'supliers#suplierReport', :as => :suplier_report
  post '/allSupliers/report' => 'supliers#allSupliersReport'

  post '/user/create' => 'users#create', :as => :user_create

  get 'debit_note/update_sales' => 'debit_notes#update_sales', :as => :update_sales

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :suplier
  belongs_to :customer
  has_one :shipping, autosave:true
  has_one :fixation, autosave:true
  
  accepts_nested_attributes_for :shipping, :fixation
  validates :rioexport_contract, :customer_id, :suplier_id, presence: true
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy, :saleReport]


  def index
    @sales = Sale.all
  end

  def show
  end

  def new
    @sale = Sale.new
    @sale.build_shipping
    @sale.build_fixation
    @supliers = Suplier.all
    @customers = Customer.all
  end

  def edit
    @sale.build_shipping if @sale.shipping.nil?
    @sale.build_fixation if @sale.fixation.nil?
  end

  def create
    @sale = Sale.new(sale_params)
    @supliers = Suplier.all
    @customers = Customer.all

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: t("activerecord.controller_msg.sale.created", :default => 'Sale was successfully created.') }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: t("activerecord.controller_msg.sale.updated", :default => 'Sale was successfully updated.') }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: t("activerecord.controller_msg.sale.destroyed", :default => 'Sale was successfully destroyed.') }
      format.json { head :no_content }
    end
  end

  
# *********************************************************************************************

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
      @supliers = Suplier.all
      @customers = Customer.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit( :rioexport_contract, 
                                    :suplier_contract, 
                                    :customer_contract, 
                                    :bags_qty, 
                                    :shipping_date, 
                                    :shipping_co_id,
                                    :price, 
                                    :payment_type,
                                    :product_type, 
                                    :customer_commission,
                                    :suplier_commission,
                                    :suplier_id, 
                                    :customer_id,
                                    shipping_attributes: [:id, 
                                                          :destination,
                                                          :shipping_line,
                                                          :daparture_terminal,
                                                          :arriving_terminal,
                                                          :special_conditions,
                                                          :documents],
                                    fixation_attributes: [:id, 
                                                          :fixed_lot,
                                                          :average_price,
                                                          :defferential,
                                                          :final_price]
                                  )
    end

end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for @sale, :html => { :class => "form-horizontal sale" } do |f| %>

  <% if @sale.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @sale.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  
  <div class="tabbable"> <!-- Only required for left/right tabs -->
    <ul class="nav nav-tabs">
      <li class="active"><a href="#tab1" data-toggle="tab"><%= t("views.sale.sale_contract", :default => 'Sale Contract') %></a></li>
      <li><a href="#tab2" data-toggle="tab"><%= t("views.sale.ship_info", :default => 'Shippment Information') %></a></li>
      <li><a href="#tab3" data-toggle="tab"><%= t("views.sale.fixation_info", :default => 'Price Fixation') %></a></li>
    </ul>
    <div class="tab-content">
      
    <!-- ************************************ INICIO TABS ****************************************-->      

    <!-- ************************************ TAB 1 ****************************************-->    
    <!-- *                                                                                 *-->    
    <!-- *                                  SALE DATA                                      *-->    
    <!-- *                                                                                 *-->    
    <!-- ************************************ TAB 1 ****************************************-->    

      <div class="tab-pane active" id="tab1">
        <br>
        <div class="form-group">
          <%= f.label :rioexport_contract, :class => 'control-label col-lg-2' %>
          <div class="col-lg-1">
            <%= f.text_field :rioexport_contract, :class => 'form-control' %>
          </div>
          <%=f.error_span(:rioexport_contract) %>
        </div>
        
        <div class="form-group">
          <%= f.label :suplier_contract, :class => 'control-label col-lg-2' %>
          <div class="col-lg-1">
            <%= f.text_field :suplier_contract, :class => 'form-control' %>
          </div>
          <%=f.error_span(:suplier_contract) %>
        </div>
        
        <div class="form-group">
          <%= f.label :customer_contract, :class => 'control-label col-lg-2' %>
          <div class="col-lg-1">
            <%= f.text_field :customer_contract, :class => 'form-control' %>
          </div>
          <%=f.error_span(:customer_contract) %>
        </div>
        
        <div class="form-group">
          <%= f.label :bags_qty, :class => 'control-label col-lg-2' %>
          <div class="col-lg-1">
            <%= f.text_field :bags_qty, :class => 'form-control' %>
          </div>
          <%=f.error_span(:bags_qty) %>
        </div>
        
        <div class="form-group">
          <%= f.label :shipping_date, :class => 'control-label col-lg-2' %>
          <div class="col-lg-1">
            <%= f.text_field :shipping_date, :class => 'form-control' %>
          </div>
          <%=f.error_span(:shipping_date) %>
        </div>
        
        <div class="form-group">
          <%= f.label :price, :class => 'control-label col-lg-2' %>
          <div class="col-lg-1">
            <%= f.text_field :price, :class => 'form-control' %>
          </div>
          <%=f.error_span(:price) %>
        </div>
        
        <div class="form-group">
          <%= f.label :product_type, :class => 'control-label col-lg-2' %>
          <div class="col-lg-2">
            <%= f.text_field :product_type, :class => 'form-control' %>
          </div>
          <%=f.error_span(:product_type) %>
        </div>
        
        <div class="form-group">
          <%= f.label :suplier_name, :class => 'control-label col-lg-2' %>
          <div class="col-lg-2">
            <%= f.collection_select(:suplier_id, @supliers, :id, :name, include_blank: true) %>
          </div>
          <%=f.error_span(:suplier_id) %>
        </div>
        
        <div class="form-group">
          <%= f.label :suplier_com_desc, :class => 'control-label col-lg-2' %>
          <div class="col-lg-1">
            <%= f.text_field :suplier_com_desc, :class => 'form-control' %>
          </div>
          <%=f.error_span(:suplier_com_desc) %>
        </div>
        
        <div class="form-group">
          <%= f.label :customer_name, :class => 'control-label col-lg-2' %>
          <div class="col-lg-2">
            <%= f.collection_select(:customer_id, @customers, :id, :name, include_blank: true) %>
          </div>
          <%=f.error_span(:customer_id) %>
        </div>
        
        <div class="form-group">
          <%= f.label :customer_com_desc, :class => 'control-label col-lg-2' %>
          <div class="col-lg-1">
            <%= f.text_field :customer_com_desc, :class => 'form-control' %>
          </div>
          <%=f.error_span(:customer_com_desc) %>
        </div>
        
        <div class="form-group">
          <%= f.label :shipping_co_id, :class => 'control-label col-lg-2' %>
          <div class="col-lg-2">
            <%= f.text_field :shipping_co_id, :class => 'form-control' %>
          </div>
          <%=f.error_span(:shipping_co_id) %>
        </div>

      </div>
      
    <!-- ************************************ TAB 2 ****************************************-->    
    <!-- *                                                                                 *-->    
    <!-- *                                SHIPPING INFO                                    *-->    
    <!-- *                                                                                 *-->    
    <!-- ************************************ TAB 2 ****************************************-->    
      
      <div class="tab-pane" id="tab2">
        <br>

        <%= f.fields_for :shipping do |sh| %>
          <div class="form-group">
            <%= sh.label :destination, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= sh.text_field :destination, :class => 'form-control' %>
            </div>
            <%=sh.error_span(:destination) %>
          </div>
          
          <div class="form-group">
            <%= sh.label :daparture_terminal, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= sh.text_field :daparture_terminal, :class => 'form-control' %>
            </div>
            <%=sh.error_span(:daparture_terminal) %>
          </div>

          <div class="form-group">
            <%= sh.label :arriving_terminal, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= sh.text_field :arriving_terminal, :class => 'form-control' %>
            </div>
            <%=sh.error_span(:arriving_terminal) %>
          </div>

          <div class="form-group">
            <%= sh.label :shipping_line, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= sh.text_field :shipping_line, :class => 'form-control' %>
            </div>
            <%=sh.error_span(:shipping_line) %>
          </div>
          
          <div class="form-group">
            <%= sh.label :special_conditions, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= sh.text_area :special_conditions, cols: "30", rows: "8", :class => 'form-control' %>
            </div>
            <%=sh.error_span(:special_conditions) %>
          </div>
          
          <div class="form-group">
            <%= sh.label :documents, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= sh.text_area :documents, cols: "60", rows: "8", :class => 'form-control' %>
            </div>
            <%=sh.error_span(:documents) %>
          </div>
          
        <% end %>

      </div>

    <!-- ************************************ TAB 3 ****************************************-->    
    <!-- *                                                                                 *-->    
    <!-- *                                PRICE FIXATION                                   *-->    
    <!-- *                                                                                 *-->    
    <!-- ************************************ TAB 3 ****************************************-->    
      <div class="tab-pane" id="tab3">
        <br>

        <%= f.fields_for :fixation do |fx| %>
          <div class="form-group">
            <%= fx.label :fixed_lot, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= fx.text_field :fixed_lot, :class => 'form-control' %>
            </div>
            <%=fx.error_span(:fixed_lot) %>
          </div>
          
          <div class="form-group">
            <%= fx.label :average_price, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= fx.text_field :average_price, :class => 'form-control' %>
            </div>
            <%=fx.error_span(:average_price) %>
          </div>

          <div class="form-group">
            <%= fx.label :diferential, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= fx.text_field :diferential, :class => 'form-control' %>
            </div>
            <%=fx.error_span(:diferential) %>
          </div>

          <div class="form-group">
            <%= fx.label :final_price, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= fx.text_field :final_price, :class => 'form-control' %>
            </div>
            <%=fx.error_span(:final_price) %>
          </div>

          <div class="form-group">
            <%= fx.label :suplier_commission, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= fx.text_field :suplier_commission, :class => 'form-control' %>
            </div>
            <%=fx.error_span(:suplier_commission) %>
          </div>

          <div class="form-group">
            <%= fx.label :ptax, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= fx.text_field :ptax, :class => 'form-control' %>
            </div>
            <%=fx.error_span(:ptax) %>
          </div>

          <div class="form-group">
            <%= fx.label :customer_commission, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= fx.text_field :customer_commission, :class => 'form-control' %>
            </div>
            <%=fx.error_span(:customer_commission) %>
          </div>
          
          <div class="form-group">
            <%= fx.label :debit_note_id, :class => 'control-label col-lg-2' %>
            <div class="col-lg-2">
              <%= fx.text_field :debit_note_id, :class => 'form-control' %>
            </div>
            <%=fx.error_span(:debit_note_id) %>
          </div>

        <% end %>

      </div>

    <!-- ************************************ FIM TABS ****************************************-->      

    </div>
  </div>  

  <table>
    <tr align="left">
      <td width="100">&nbsp;</td>
      <td>
        <%=  image_submit_tag('confirm2.png', :border => 0, :alt => '', :title => t("helpers.links.save", :default => 'Save'), :width => 40, :height => 40) %>
      </td>
      <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td>
        <%= link_to image_tag('cancel.png', :border => 0, :alt => '', :title => t("helpers.links.cancel", :default => 'Cancel'), :width => 40, :height => 40),
                    sales_path
        %>
      </td>
    </tr>
  </table>
<% end %>

app/views/sales/_sale.html.erb
<option value="<%= sale.id %>"><%= sale.customer_contract %></option>

app/views/sales/edit.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/index.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1>
      <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
  </h1>
</div>
<table class="table table-striped">
<!--<table class="table table-responsive">-->
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:customer_name) %></th>
      <th><%= model_class.human_attribute_name(:suplier_name) %></th>
      <th><%= model_class.human_attribute_name(:shipping_co_id) %></th>
      <th><%= model_class.human_attribute_name(:shipping_date) %></th>
      <th><%= model_class.human_attribute_name(:product_type) %></th>
      <th colspan="5"><div align="center"><%=t '.actions', :default => t("helpers.actions") %></div></th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to sale.id, sale_path(sale) %></td>
        <td><%= sale.customer.name %></td>
        <td><%= sale.suplier.name %></td>
        <td><%= sale.shipping_co_id %></td>
        <td><%= sale.shipping_date %></td>
        <td><%= sale.product_type %></td>
        <td>
          <!--
          <'%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sale_path(sale), :class => 'btn btn-default btn-xs' %>
          <'%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sale_path(sale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <'%= link_to t('.print', :default => t("helpers.links.print")),
                      sale_report_path(sale),
                      method: :post,
                      :class => 'btn btn-primary' %>
          -->
          <%= link_to image_tag('edit.png', :border => 0, :alt => '', :title => t("views.sale.edit", :default => 'Edit Sale'), :width => 20, :height => 20),
                      edit_sale_path(sale)
          %>
        </td>
        <td>
          <%= link_to image_tag('delete.png', :border => 0, :alt => '', :title => t("views.sale.destroy", :default => 'Delete Sale'), :width => 20, :height => 20),
                      sale_path(sale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure ?')) }
          %>
        </td>
        <td>
          <%= link_to image_tag('printer.png', :border => 0, :alt => '', :title => t("views.sale.report", :default => 'Sale Report'), :width => 20, :height => 20),
                      sale_report_path(sale),
                      method: :post
          %>
        </td>
        <td>
          <%= link_to image_tag('printer.png', :border => 0, :alt => '', :title => t("views.sale.suplier_report", :default => 'Suplier Sale Report'), :width => 20, :height => 20),
                      suplier_sale_report_path(sale),
                      method: :post
          %>
        </td>
        <td>
          <%= link_to image_tag('printer.png', :border => 0, :alt => '', :title => t("views.sale.customer_report", :default => 'Customer Sale Report'), :width => 20, :height => 20),
                      customer_sale_report_path(sale),
                      method: :post
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!--
<'%= link_to t('.new', :default => t("helpers.links.new")), new_sale_path, :class => 'btn btn-primary' %>

<'%= link_to t('.print', :default => t("helpers.links.print")), allSales_report_path, method: :post, :class => 'btn btn-primary' %>
-->
<table>
  <tr align="left">
    <td>
        <%= link_to image_tag('new.png', :border => 0, :alt => '', :title => t("views.sale.new", :default => 'New Sale'), :width => 40, :height => 40),
                    new_sale_path
        %>
    </td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td>
        <%= link_to image_tag('printer.png', :border => 0, :alt => '', :title => t("views.sale.allReport", :default => 'Sales Report'), :width => 40, :height => 40),
                              allSales_report_path(:format => :pdf),
                              method: :post
        %>
    </td>
  </tr>
</table>

app/views/sales/new.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/show.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:rioexport_contract) %>:</strong></dt>
  <dd><%= @sale.rioexport_contract %></dd>
  <dt><strong><%= model_class.human_attribute_name(:suplier_contract) %>:</strong></dt>
  <dd><%= @sale.suplier_contract %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_contract) %>:</strong></dt>
  <dd><%= @sale.customer_contract %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shipping_co_id) %>:</strong></dt>
  <dd><%= @sale.shipping_co_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bags_qty) %>:</strong></dt>
  <dd><%= @sale.bags_qty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shipping_date) %>:</strong></dt>
  <dd><%= @sale.shipping_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @sale.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:product_type) %>:</strong></dt>
  <dd><%= @sale.product_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_commission) %>:</strong></dt>
  <dd><%= @sale.fixation.customer_commission %></dd>
  <dt><strong><%= model_class.human_attribute_name(:suplier_name) %>:</strong></dt>
  <dd><%= @sale.suplier.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_name) %>:</strong></dt>
  <dd><%= @sale.customer.name %></dd>
</dl>

<!--
<%= link_to t('.back', :default => t("helpers.links.back")),
              sales_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sale_path(@sale), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sale_path(@sale),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure ?')) },
              :class => 'btn btn-danger' %>
-->

  <table>
    <tr align="left">
      <td width="100">&nbsp;</td>
      <td>
        <%= link_to image_tag('back.png', :border => 0, :alt => '', :title => t("helpers.links.back", :default => 'Back'), :width => 40, :height => 40),
                    sales_path
        %>
      </td>
      <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td>
          <%= link_to image_tag('edit.png', :border => 0, :alt => '', :title => t("views.sale.edit", :default => 'Edit Sale'), :width => 40, :height => 40),
                      edit_sale_path(@sale)
          %>
      </td>
      <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td>
          <%= link_to image_tag('delete.png', :border => 0, :alt => '', :title => t("views.sale.destroy", :default => 'Delete Sale'), :width => 40, :height => 40),
                      sale_path(@sale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure ?')) }
          %>
      </td>
    </tr>
  </table>