config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'visitors#index'

  resources :sales
  resources :customers
  resources :supliers
  resources :users
  resources :debit_notes
  

  post '/customer/report' => 'customers#customerReport', :as => :customer_report
  post '/allCustomers/report' => 'customers#allCustomersReport'

  post '/sale/:id/report' => 'reports#saleReport', :as => :sale_report
  post '/suplier_sale/:id/report' => 'reports#suplierSaleReport', :as => :suplier_sale_report
  post '/customer_sale/:id/report' => 'reports#customerSaleReport', :as => :customer_sale_report
  post '/allSales/report' => 'reports#allSalesReport'

  post '/suplier/:id/report' => 'supliers#suplierReport', :as => :suplier_report
  post '/allSupliers/report' => 'supliers#allSupliersReport'

  post '/user/create' => 'users#create', :as => :user_create

  get 'debit_note/update_sales' => 'debit_notes#update_sales', :as => :update_sales

end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="container">
  <hr>
  <footer>
      <div class="row">
          <div class="col-lg-12">
              <p>Copyright &copy; RioExport 2016</p>
          </div>
      </div>
  </footer>
</div>
<!-- /.container -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to t('layout.customers'), customers_path %></li>
  <li><%= link_to t('layout.supliers'), supliers_path %></li>
  <li><%= link_to t('layout.sales'), sales_path %></li>
  <li><%= link_to t('layout.edit_account'), edit_user_registration_path %></li>
  <li><%= link_to t('layout.sign_out'), destroy_user_session_path, :method=>'delete' %></li>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/nav_links_for_auth' %>
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li><%= link_to t('layout.customers'), customers_path %></li>
  <li><%= link_to t('layout.supliers'), supliers_path %></li>
  <li><%= link_to t('layout.sales'), sales_path %></li>
  <li><%= link_to t('layout.debit_notes'), debit_notes_path%></li>
  <li><%= link_to t('layout.edit_account'), edit_user_registration_path %></li>
  <li><%= link_to t('layout.sign_out'), destroy_user_session_path, :method=>'delete' %></li>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

app/views/layouts/_navigation_links_old.html.erb
<%# add navigation links to this file %>
<li><%= link_to t('layout.about'), page_path('about') %></li>

app/views/layouts/_navigation_old.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/nav_links_for_auth' %>
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RioExport" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "RioExport" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'coffee_bean3.png' %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script src="assets/jquery-1.12.4.js"></script>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RioExport" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "RioExport" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'coffee_bean3.png' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>